import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./Components/NavBar";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Alfred Cards",
  description: "Generated by Team Alfred AI",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  const {getUser} = getKindeServerSession();
  const user = await getUser();

  return (
    <html lang="en">
      <body className={inter.className}><NavBar user={user}/>{children}</body>
    </html>
  );
}
